import { prisma } from "@/lib/prisma";

// Position-based points structures
const NASCAR_POINTS = {
  "1": 40,
  "2": 34,
  "3": 32,
  "4": 31,
  "5": 30,
  "6": 29,
  "7": 28,
  "8": 27,
  "9": 26,
  "10": 25,
  "11": 24,
  "12": 23,
  "13": 22,
  "14": 21,
  "15": 20,
  "16": 19,
  "17": 18,
  "18": 17,
  "19": 16,
  "20": 15,
  "21": 14,
  "22": 13,
  "23": 12,
  "24": 11,
  "25": 10,
  "26": 9,
  "27": 8,
  "28": 7,
  "29": 6,
  "30": 5,
  "31": 4,
  "32": 3,
  "33": 2,
  "34": 1,
  "35": 0,
  "36": 0,
  "37": 0,
  "38": 0,
  "39": 0,
  "40": 0,
};

const F1_POINTS = {
  "1": 25,
  "2": 18,
  "3": 15,
  "4": 12,
  "5": 10,
  "6": 8,
  "7": 6,
  "8": 4,
  "9": 2,
  "10": 1,
  "11": 0,
  "12": 0,
  "13": 0,
  "14": 0,
  "15": 0,
  "16": 0,
  "17": 0,
  "18": 0,
  "19": 0,
  "20": 0,
  "21": 0,
  "22": 0,
  "23": 0,
  "24": 0,
  "25": 0,
  "26": 0,
  "27": 0,
  "28": 0,
  "29": 0,
  "30": 0,
  "31": 0,
  "32": 0,
  "33": 0,
  "34": 0,
  "35": 0,
  "36": 0,
  "37": 0,
  "38": 0,
  "39": 0,
  "40": 0,
};

const INDYCAR_POINTS = {
  "1": 50,
  "2": 40,
  "3": 35,
  "4": 32,
  "5": 30,
  "6": 28,
  "7": 26,
  "8": 24,
  "9": 22,
  "10": 20,
  "11": 19,
  "12": 18,
  "13": 17,
  "14": 16,
  "15": 15,
  "16": 14,
  "17": 13,
  "18": 12,
  "19": 11,
  "20": 10,
  "21": 9,
  "22": 8,
  "23": 7,
  "24": 6,
  "25": 5,
  "26": 4,
  "27": 3,
  "28": 2,
  "29": 1,
  "30": 0,
  "31": 0,
  "32": 0,
  "33": 0,
  "34": 0,
  "35": 0,
  "36": 0,
  "37": 0,
  "38": 0,
  "39": 0,
  "40": 0,
};

const STANDARD_BONUS = {
  pole: 1,
  raceWinner: 5,
  stageWin: 0,
  stageFinish1: 0,
  stageFinish2: 0,
  stageFinish3: 0,
  stageFinish4: 0,
  stageFinish5: 0,
  stageFinish6: 0,
  stageFinish7: 0,
  stageFinish8: 0,
  stageFinish9: 0,
  stageFinish10: 0,
  ledMostLaps: 2,
  ledOneOrMoreLaps: 1,
  gainedMostPositions: 1,
  lostMostPositions: 0,
  fastestLap: 1,
  noIncidents: 2,
  finishRace: 0,
  fastestAverage: 0,
  finishNoIncidents: 1,
};

const NASCAR_STAGE_BONUS = {
  ...STANDARD_BONUS,
  stageWin: 1,
  stageFinish1: 10,
  stageFinish2: 9,
  stageFinish3: 8,
  stageFinish4: 7,
  stageFinish5: 6,
  stageFinish6: 5,
  stageFinish7: 4,
  stageFinish8: 3,
  stageFinish9: 2,
  stageFinish10: 1,
};

// Common points systems used in racing/iRacing
const DEFAULT_POINTS_SYSTEMS = [
  {
    name: "NASCAR Cup Series",
    description:
      "NASCAR-style points system with standard race finish and bonus point structure",
    positionPoints: NASCAR_POINTS,
    bonusPoints: NASCAR_STAGE_BONUS,
    isPreset: true,
    presetType: "nascar",
  },
  {
    name: "Formula 1",
    description:
      "F1-style points for top 10 finishers with bonus points integration",
    positionPoints: F1_POINTS,
    bonusPoints: {
      pole: 3,
      raceWinner: 0,
      fastestLap: 1,
      noIncidents: 0,
    },
    isPreset: true,
    presetType: "f1",
  },
  {
    name: "IndyCar Series",
    description:
      "IndyCar-style points system with emphasis on race winners and top finishers",
    positionPoints: INDYCAR_POINTS,
    bonusPoints: {
      pole: 2,
      raceWinner: 3,
      ledMostLaps: 2,
      ledOneOrMoreLaps: 1,
      fastestLap: 1,
      noIncidents: 1,
    },
    isPreset: true,
    presetType: "indycar",
  },
  {
    name: "Standard (25-20-16-13-10-8-6-4-2-1)",
    description: "Standard iRacing/NASCAR official points system",
    positionPoints: {
      "1": 25,
      "2": 20,
      "3": 16,
      "4": 13,
      "5": 10,
      "6": 8,
      "7": 6,
      "8": 4,
      "9": 2,
      "10": 1,
      ...[...Array(30)].reduce(
        (acc, _, i) => ({ ...acc, [`${i + 11}`]: 0 }),
        {},
      ),
    },
    bonusPoints: STANDARD_BONUS,
    isPreset: false,
  },
  {
    name: "Simple (10-8-6-4-2-1)",
    description: "Simple points system for casual leagues",
    positionPoints: {
      "1": 10,
      "2": 8,
      "3": 6,
      "4": 4,
      "5": 2,
      "6": 1,
      ...[...Array(34)].reduce(
        (acc, _, i) => ({ ...acc, [`${i + 7}`]: 0 }),
        {},
      ),
    },
    bonusPoints: { pole: 0, raceWinner: 0, fastestLap: 0, noIncidents: 0 },
    isPreset: false,
  },
  {
    name: "Participation (6-5-4-3-2-1)",
    description: "Points awarded for participation, good for fun leagues",
    positionPoints: {
      "1": 6,
      "2": 5,
      "3": 4,
      "4": 3,
      "5": 2,
      "6": 1,
      ...[...Array(34)].reduce(
        (acc, _, i) => ({ ...acc, [`${i + 7}`]: 0 }),
        {},
      ),
    },
    bonusPoints: { pole: 0, noIncidents: 1 },
    isPreset: false,
  },
  {
    name: "Winner-Heavy (50-30-20-15-10-5-2-1)",
    description: "Points system with heavier emphasis on race winner",
    positionPoints: {
      "1": 50,
      "2": 30,
      "3": 20,
      "4": 15,
      "5": 10,
      "6": 5,
      "7": 2,
      "8": 1,
      ...[...Array(32)].reduce(
        (acc, _, i) => ({ ...acc, [`${i + 9}`]: 0 }),
        {},
      ),
    },
    bonusPoints: { raceWinner: 10, pole: 2, fastestLap: 1 },
    isPreset: false,
  },
];

export async function seedDefaultPointsSystems() {
  try {
    for (const system of DEFAULT_POINTS_SYSTEMS) {
      const exists = await prisma.seriesPointsSystem.findFirst({
        where: {
          name: system.name,
          leagueId: null, // Global systems have no leagueId
        },
      });

      if (!exists) {
        await prisma.seriesPointsSystem.create({
          data: {
            name: system.name,
            description: system.description,
            positionPoints: system.positionPoints,
            bonusPoints: system.bonusPoints,
            isDefault: system.name.startsWith("NASCAR"),
            isPreset: system.isPreset || false,
            presetType: system.presetType || null,
            leagueId: null,
          },
        });
        console.log(`[seed] Created default points system: ${system.name}`);
      }
    }
  } catch (error) {
    console.error("[seed] Error seeding default points systems:", error);
  }
}
